# Generated by Django 4.2 on 2025-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastnames',
            field=models.CharField(default='', max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='names',
            field=models.CharField(default='', max_length=50, verbose_name='Nombres'),
        ),
    ]
