# Generated by Django 4.2 on 2025-01-13 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tareas',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tareas',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
