# Generated by Django 4.2 on 2025-01-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_tareas_active_tareas_create_date_tareas_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
