# Generated by Django 4.2 on 2025-01-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_historiausuario_slug_incidencias_slug_tareas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
