# Generated by Django 4.2 on 2025-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_historiausuario_slug_alter_incidencias_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidencias',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareas',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
