# Generated by Django 4.2 on 2025-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_comentarios_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidencias',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareas',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
