# Generated by Django 4.2 on 2025-02-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_historiausuario_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
